# Generated by Django 4.0.4 on 2022-05-22 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerDouble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_double', models.TextField()),
                ('create_date_double', models.DateTimeField()),
                ('modify_date_double', models.DateTimeField(blank=True, null=True)),
                ('author_double', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_answer_double', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionDouble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_double', models.CharField(max_length=200)),
                ('content_double', models.TextField()),
                ('create_date_double', models.DateTimeField()),
                ('modify_date_double', models.DateTimeField(blank=True, null=True)),
                ('author_double', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_question_double', to=settings.AUTH_USER_MODEL)),
                ('voter_double', models.ManyToManyField(related_name='voter_question_double', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentDouble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_double', models.TextField()),
                ('create_date_double', models.DateTimeField()),
                ('modify_date_double', models.DateTimeField(blank=True, null=True)),
                ('answer_double', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doubleboard.answerdouble')),
                ('author_double', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question_double', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doubleboard.questiondouble')),
            ],
        ),
        migrations.AddField(
            model_name='answerdouble',
            name='question_double',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doubleboard.questiondouble'),
        ),
        migrations.AddField(
            model_name='answerdouble',
            name='voter_double',
            field=models.ManyToManyField(related_name='voter_answer_double', to=settings.AUTH_USER_MODEL),
        ),
    ]
