# Generated by Django 4.0.4 on 2022-05-22 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerFree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_free', models.TextField()),
                ('create_date_free', models.DateTimeField()),
                ('modify_date_free', models.DateTimeField(blank=True, null=True)),
                ('author_free', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_answer_free', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionFree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_free', models.CharField(max_length=200)),
                ('content_free', models.TextField()),
                ('create_date_free', models.DateTimeField()),
                ('modify_date_free', models.DateTimeField(blank=True, null=True)),
                ('author_free', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_question_free', to=settings.AUTH_USER_MODEL)),
                ('voter_free', models.ManyToManyField(related_name='voter_question_free', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentFree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_free', models.TextField()),
                ('create_date_free', models.DateTimeField()),
                ('modify_date_free', models.DateTimeField(blank=True, null=True)),
                ('answer_free', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='free.answerfree')),
                ('author_free', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question_free', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='free.questionfree')),
            ],
        ),
        migrations.AddField(
            model_name='answerfree',
            name='question_free',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='free.questionfree'),
        ),
        migrations.AddField(
            model_name='answerfree',
            name='voter_free',
            field=models.ManyToManyField(related_name='voter_answer_free', to=settings.AUTH_USER_MODEL),
        ),
    ]
